### ISSUE TITLE
Feature request: weight units

### ISSUE THREAD

**Issue by zz0rk** [tchar/ulauncher-albert-calculate-anything#1]
I am unable to convert e.g. cups to grams. I've installed all prerequisites as per setup instructions.

= 1 cup to gram

Thanks

**Comment by tchar** [comment]
Hello.

Do other conversions work?

Cups measure volume, but grams measure mass. You could convert cups to litters or milliliter but not to mass.

I'm working on including custom units but it is not easy to decide how to name them so I don't overwrite the default units.

**Comment by zz0rk** [comment]
Yes, that's what I figured. Everything else works really well. It's very convenient to do all of these conversions from within Ulauncher. Great work! Thanks, char!

**Comment by tchar** [comment]
Thanks,

I am closing for now, feel free to reopen.

As I said I am working on including custom units. I have alreaded integrated currency to the unit system, but I realized  that you can now do conversiont that don't make sense in real life, but make sense mathematically (like 10 EUR * litter to CAD * cup)

Once I figure a way to solve this I will try to allow custom units. [pint docs](https://pint.readthedocs.io/en/stable/defining.html)
