### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lululoid** [tchar/ulauncher-albert-calculate-anything#31]
No function work, just loading...

**Comment by tchar** [comment]
Hello @lululoid 

Would you mind providing some more information?

Like what launcher, how did you install, any logs, operating system, did you install python modules needed?

I cannot help you if you just say "not working"

Thanks

**Comment by lululoid** [comment]
Nevermind @tchar, after ulauncher upgrade it's now work perfectly.
