### ISSUE TITLE
[bug] Calculation error sin(2*pi)

### ISSUE THREAD

**Issue by ChrisS85** [tchar/ulauncher-albert-calculate-anything#40]
## Describe the bug
= sin(2*pi) gives 1 instead of 0 on ULauncher

## Expected behavior
Should be 0.

## Logs
[runtime.log](https://github.com/tchar/ulauncher-albert-calculate-anything/files/8827724/runtime.log)

## Screenshots
![grafik](https://user-images.githubusercontent.com/979461/171735017-14fcd50d-eee6-4f1b-a40d-d2a58671d8f4.png)

## Desktop (please complete the following information)
 - OS: Xubuntu 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tchar** [comment]
Fixed #49 .
