### ISSUE TITLE
[bug] Crashed on Ulauncher 5.14.7

### ISSUE THREAD

**Issue by Bishal-Mahanta** [tchar/ulauncher-albert-calculate-anything#41]
## Describe the bug
Calculate anything crashes everytime ulauncher is launched.

## To Reproduce
Just add the extension for Calculate Anything on Ulauncher.

## Expected behavior
Proper output when given command.

## Logs
[runtime.log.zip](https://github.com/tchar/ulauncher-albert-calculate-anything/files/9280725/runtime.log.zip)

## Screenshots
![Screenshot_20220808_151723](https://user-images.githubusercontent.com/64310226/183390244-c5322a7b-976e-41ee-ad4a-33295d33aace.png)
![Screenshot_20220808_151753](https://user-images.githubusercontent.com/64310226/183390249-ca6e0826-6ceb-4272-b013-3e89ecab4df4.png)

## Desktop (please complete the following information)
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.8
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.15.0-43-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i3-8130U CPU @ 2.20GHz
Memory: 15.4 GiB of RAM

**Comment by tchar** [comment]
There is a division by zero here in currency can you reinstall the extension? I will have to handle this when the currency rate is 0 or (1 / rate overflows)
